### ISSUE TITLE
Rewrite of the plugin

### ISSUE THREAD

**Issue by mhyllander** [futuresimple/helm-secrets#52] opened 2018-06-08 09:56 UTC
Hi @szibis 

I wanted to show you a rewrite I have done of helm-secrets.
https://github.com/mhyllander/helm-secrets/tree/fixes

I find the plugin idea very useful and it would have solved the problems I and my team had when starting to use kubernetes and helm. But I had some problems using it, so I started on a fork and ended up rewriting most of the plugin.

1. There is some confusion in the current plugin whether it should decrypt template files or not. Documentation and implementation are not in sync. My design decision is that template files should not contain secrets. Secrets should only be stored in value files, by convention named "secrets.yaml" (or "secrets.\*.yaml" if you need several). The decrypted files are named "secrets.dec.yaml" or "secrets.\*.dec.yaml".
2. I have included the wrapper inside the plugin, so instead of running "helm-wrapper install ...", you run "helm secrets install ...". Etc. The wrapper function does intelligent parsing of command line options.
3. The wrapper no longer scans the chart for files to decrypt. It only decrypts value files specified with the -f and --values options on the command line (and removes the on-the-fly decrypted files after the helm command has been run).

I realize my changes are probably too much to be merged back to this repo (and maybe I haven't encountered all use cases), but I wanted to notify you about my fork in case you were interested.

**Comment by szibis** [comment] 2018-07-04 06:05
We can talk about merging this. But we need to have some backward compatibility.
1. Yes, this is correct. Doc should be extended.
2. This looks ok.
3. We can use some flags in configuration to specify default behaviour.

Can you prepare some PR to look at this?

**Comment by pesimon** [comment] 2018-07-30 08:08
Hi @mhyllander - I like the approach of your fixes branch since is less invasive.

However on my MacOS  `declare -n` is not supported. 
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

**Comment by mhyllander** [comment] 2018-08-01 08:01
Hi @szibis - sorry I have been on vacation and just came back. I'll start preparing a PR.

Hi @pesimon - yes, I've heard from members of my team who use MacOS that they needed to install bash version 4 to get it to work. I'll modify the function to support previous bash versions also.

**Comment by mhyllander** [comment] 2018-08-01 12:13
@szibis, I've cleaned up my commits and created a PR from a new branch.

**Comment by jrnt30** [comment] 2018-08-14 19:32
I am curious on the decryption process what the idea is behind the removal of the `.dec` suffix.  It seems simpler to reason about and additionally makes external tools using this (helmfile in this case) easier to reason about what `helm secrets dec` will do.

**Comment by jrnt30** [comment] 2018-08-15 13:10
Thanks for the context. The input and output type is how we had approached
a custom fork for a customer.

Personally I think it's a bit cleaner and easier to consume bit I can make
either work.

**Comment by mhyllander** [comment] 2018-08-16 14:42
I tested going back to the .yaml.dec suffix and it was straight-forward. I also added the possibility to override the default suffix using an environment variable.

So I'm entirely open to changing back, especially since it turned out the change wasn't really necessary.

**Comment by mhyllander** [comment] 2018-08-17 11:05
OK, I pushed the commit that reverts to using .yaml.dec for decrypted files. #60

**Comment by RoryShively** [comment] 2018-10-03 17:11
I'm working on making skaffold compatible with helm secrets. Skaffold will use the command 
```
helm-wrapper --kube-context minikube install --name autotool charts/autotool --namespace qt-development -f charts/autotool/helm_vars/values.yaml -f charts/autotool/helm_vars/secrets.yaml --set image.repository=autotool:07312a3-dirty-99ce0dd --set image.tag=
```
with more or less flags to install the helm package.

Problem is helm secrets breaks because it confuses some of the flags with chart names. not sure if its the positioning of the flags or if it's the names. I'm not remotely competent in bash so finding a root cause is hard for me.

I'm going to try and work this out when I have time but if you could consider this in your rewrite it would be greatly appreciated

**Comment by mhyllander** [comment] 2018-10-04 08:53
@RoryShively The rewrite I have done should handle parsing of the command line correctly. I have moved the wrapper into the secrets plugin itself, instead of having a separate shell script. Your command becomes:

``` bash
helm secrets --kube-context minikube install --name autotool charts/autotool --namespace qt-development -f charts/autotool/helm_vars/values.yaml -f charts/autotool/helm_vars/secrets.yaml --set image.repository=autotool:07312a3-dirty-99ce0dd --set image.tag=
```

helm will first handle (and remove) global flags like `--kube-context`. Then the remaining flags and arguments are passed to the secrets plugin, which parses them using `getopt`. This is more robust than the original wrapper. (The current wrapper is actually buggy: First it loops over the command line arguments and tries to decrypt anything that matches regex `.*secrets.y*` (sic). Then it treats the command line as a single string and replaces all occurrences of "secrets.yaml" with "secrets.yaml.dec" before it's executed. This can easily go wrong because it has no idea of what is what on the command line).

`helm install --help` specifies `Usage: helm install [CHART] [flags]`, but it's my experience that flags can be placed anywhere on the command line, while arguments must come after the commands and in the correct order (just like in the example above).

**Comment by justicel** [comment] 2018-10-17 17:36
Are we any closer to getting this merged? It has some pretty big additions that I at least would find super useful.

**Comment by RoryShively** [comment] 2018-10-17 18:12
@mhyllander I tested it out and one thing that I'm noticing is if I try and specify a name in the command
e.x. `helm secrets --kube-context minikube install helm_test --name helm_test -f helm_test/helm_vars/values.yaml -f helm_test/helm_vars/secrets.yaml`
I get an error in my output
```
NAME:   helm_test
Error: getting deployed release "helm_test": release: "helm_test" not found
helm_test/helm_vars/secrets.yaml.dec
```

That happens whether I use `-n`, `--name`, or if I switch the position of the arguement.

BUT, if I leave the name arg out everything works properly

**Comment by mhyllander** [comment] 2018-10-17 19:59
@RoryShively I think this may be a bug in helm itself: https://github.com/helm/helm/issues/3493

**Closed** 2018-10-22 12:34 UTC
Labels: enhancement
